language: java

jobs:
  include:
    - stage: "Build"
      install: skip
      script: ./gradlew shadowJar && ./run.sh -h
    - stage: "Lint"
      script: ./gradlew lintKotlin && ./gradlew detekt
    - stage: "Test"
      script: ./gradlew test && ./gradlew jacocoTestReport
      after_success: bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
